const String loginSuccess ="Login_Success";
const String tokenUser = "Token_User";
const String userName ="User_Name";
const String password ="Password";
const String email = "Email";
const String rememberMe = "Remember";
const String totalListEvent = "Total_List_Event";
const String checkTicket = "Check_Ticket";
const String sumTicket = "Sum_Ticket";